Test index rebuild setup.
ensi-platform/laravel-elastic-query-specification pull request #3
Opened 2022-02-17 17:35 UTC by zix2

2022-04-18 13:46 UTC, arrilot requested changes

2022-04-18 13:46 UTC, arrilot commented on tests/Data/IndexSeeder.php
>          foreach ($this->fixtures as $fixture) {
Я бы это и sleep вынес бы в отдельный метод $this->loadFixtures().
Также sleep имеет смысл вызывать только если fixtures не пустой, иначе мы просто так ждем 1 секунду

2022-04-18 13:46 UTC, arrilot commented on tests/Data/IndexSeeder.php
> +        sleep(1);
наверное что-то типа sleep(static::ELASTICSEARCH_REFRESH_TIMEOUT) будет более читабельным и менее похожим на забытый дебаг код

2022-04-19 17:25 UTC, zix2 commented on tests/Data/IndexSeeder.php
>          foreach ($this->fixtures as $fixture) {
Переделал с проверкой наличия загруженных данных.

2022-04-19 17:25 UTC, zix2 commented on tests/Data/IndexSeeder.php
> +        sleep(1);
Сделал вызов refresh вместо sleep.

2022-04-20 12:05 UTC, merged